name: 'tv-guide'
services:
  tv-guide-db:
    image: postgres:14.1-alpine
    container_name: 'tv-guide.database'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    environment:
      - POSTGRES_USER=tvg
      - POSTGRES_PASSWORD=local
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgres/data
volumes:
  db:
    driver: local
